### PR TITLE
Imperial Lbs - WIP

### PR DESCRIPTION
**Pull request by tinkeringtuck**
- added the ability to read weight if scale is lb mode 
- included .gitignore for future support for development (to gitignore files like YAGCC, etc.)

### CODE REVIEW

**Comment by tinkeringtuck** [comment]
@RobertWojtowicz Please consider this a work in progress, and please provide any feedback or suggestions. I did not find any contribution guidelines for your project, but please let me know if I missed those. I would like the ability to keep my scale in lb mode (instead of kg). I wanted to change as little as possible about your existing code, so I only added the ability to read from the scale in lbs and then converted that back to kg for the rest of the remaining code. I found how to do that in this project here https://github.com/lolouk44/xiaomi_mi_scale/blob/master/src/Xiaomi_Scale.py#L311

More extensive support throughout the code for lbs would be great, though I'm not sure it is necessary for my needs. If you think it would be helpful, and would be willing to share some ideas for where in the code should be updated, I'd be happy to work on that as well.

**Comment by RobertWojtowicz** [comment]
Hi @tinkeringtuck

This needs to be implemented at a different level, so that it is universal for BLE and ESP32, it seems that the appropriate place would be the import_data.sh script with an appropriate switch between kg and lbs.

BR,
Robert

**Comment by tinkeringtuck** [comment]
Good point. I can work on some development/testing for that on the BLE side. Unfortunately, I won't be able to do any testing for ESP32. I will push changes here in this PR and let you know when I have a proposal.

**Comment by RobertWojtowicz** [comment]
It is nothing difficult to make the counting in the  import_data.sh script only I have to find the time :)

**Comment by RobertWojtowicz** [comment]
@tinkeringtuck 

```Weight = (((data[12] & 0xFF) << 8) | (data[11] & 0xFF)) * 0.005```

this is reading the value for kg, what is the value for lbs if we left it like this, what would have to be done to normalize it in the import.sh script as kg ?

BR,
Robert

**Comment by tinkeringtuck** [comment]
> @tinkeringtuck
> 
> `Weight = (((data[12] & 0xFF) << 8) | (data[11] & 0xFF)) * 0.005`
> 
> this is reading the value for kg, what is the value for lbs if we left it like this, what would have to be done to normalize it in the import.sh script as kg ?
> 
> BR, Robert

sorry for the delay, the holidays have not provided much time for investigation. Thanks for continuing to make progress and put effort towards it. To answer your question, I'm not sure. How did you derive or discover `Weight = (((data[12] & 0xFF) << 8) | (data[11] & 0xFF)) * 0.005` for kg? I'm not sure how to go about this for lbs. Reviewing the import.sh, I had a few ideas:

- it seems that you could set an environment var in import.sh, which then get's passed to scanner_ble.py, but a similar approach would need to be implemented in esp32. I think you mentioned this was undesirable
- alternatively ble32 and scanner_ble.py could read the raw data and pass it back to import.sh for manipulation, this seems like it would have other challenges that I haven't thought through but I don't like this either
- I think the best approach, would be to change the data read in both scanner_ble and esp32 so that it works for lbs or for kg without needing the user to set a var, the proposed change was a step in that direction but perhaps more could be done or it could be improved.

**Pull request merged**
